### ISSUE TITLE
build.sh by github actions

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#4]
I tried running the command `bash build.sh` in a github action, but it throws the error:
**tput: No value for $TERM and no -T specified**

If that is an error you are familiar with, I am happy about pointers, otherwise I continue the search on my own.

<details>
<summary>full ci file</summary>

```yaml
name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb
          sudo dpkg -i pandoc-2.13-1-amd64.deb

      - name: Run build
        run: bash build.sh
```
</details>
